### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by amejid** [amejid/shopping-on-rails#9]
We are a group of two people

- Member A @amejid 
- Member B @rex-9 

Tasks description and classification can be found [here](https://github.com/users/amejid/projects/2)

**Comment by rloterh** [comment]
Hi Rex & Abdelmejid, 

Good job so far! 👏 👏 There are however a few issues that you still need to work on, but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Fair distribution of tasks

## Required Changes ♻️
- [ ] Some of your tasks do not have description provided. Kindly ensure to add descriptions to all task accordingly.

**No task descriptions:**
![image](https://user-images.githubusercontent.com/12745474/200277823-59ead387-f281-43b1-a119-57a3b064af39.png)
![image](https://user-images.githubusercontent.com/12745474/200277904-ef3176af-432f-4987-b73b-c2e64e3450fb.png)

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by amejid** [comment]
Thank you for the feedback, changes were implemented accordingly.

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Rex & Abdelmejid,  

Your project is complete! 🍾🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Fair distribution of tasks

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by amejid** [comment]
Thanks for reviewing and approving our work.
